# Generated by Django 4.1.7 on 2023-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pape', '0006_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='novedad',
        ),
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.CharField(choices=[('activo', 'primary'), ('inactivo', 'secondary'), ('eliminado', 'danger')], default='activo', max_length=10),
        ),
    ]
