# Generated by Django 4.1.7 on 2024-05-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lugar', models.CharField(blank=True, max_length=10)),
                ('categoria', models.CharField(blank='', choices=[('escolar', 'escolar'), ('papel_hule', 'papel_hule'), ('regalos_fiestas', 'regalos_fiestas'), ('monografias', 'monografias'), ('biografias', 'biografias'), ('animales', 'animales'), ('animales_marinos', 'animales_Marinos'), ('microorganismos', 'microorganismos'), ('aves', 'aves'), ('flores', 'flores'), ('comestibles', 'comestibles'), ('arboles', 'arboles'), ('dinosaurios', 'dinosaurios'), ('acontecimientos', 'acontecimientos'), ('mapas_esquemas', 'mapas_esquemas')], default='escolar', max_length=20)),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
