# Generated by Django 5.0.6 on 2024-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pape', '0002_products_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.CharField(blank='', choices=[('escolar', 'escolar'), ('papel', 'papel'), ('regalos_fiestas', 'regalos_fiestas'), ('monografias', 'monografias'), ('biografias', 'biografias'), ('animales', 'animales'), ('animales_marinos', 'animales_Marinos'), ('microorganismos', 'microorganismos'), ('aves', 'aves'), ('flores', 'flores'), ('comestibles', 'comestibles'), ('arboles', 'arboles'), ('dinosaurios', 'dinosaurios'), ('acontecimientos', 'acontecimientos'), ('mapas', 'mapas'), ('esquemas', 'esquemas'), ('hule', 'hule')], default='escolar', max_length=20),
        ),
    ]
