# Generated by Django 5.0.6 on 2024-05-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pape', '0005_rename_products_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.FloatField(),
        ),
    ]
